application: mogu-mmggoo
version: mogu3-2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: swf/Mogu.html
  upload: swf/Mogu.html

- url: /js
  static_dir: js

- url: /image
  static_dir: image
- url: /css
  static_dir: css

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /swf
  static_dir: swf
  expiration : "1d"
  secure: optional

- url: /assets
  static_dir: swf/assets
  expiration : "1d"
  secure: optional

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
